version: '3'

services:

  db:
    image: postgres:12.5
    restart: always
    environment:
      POSTGRES_PASSWORD: "12345678"
    ports:
     - "5432:5432"
    volumes:
     - /var/postgresql/data2:/var/lib/postgresql/data2
    networks:
     - postgresql
    container_name: postgres

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "12345678"
      CONSOLE_LOG_LEVEL: 60
      FILE_LOG_LEVEL: 60
      LOG_FILE: "/usr/local/bin/pgadmin4.log"
    ports:
     - "80:80"
    depends_on:
     - db
    networks:
     - postgresql

  #backend:
    #image: uber42/uisbackend:V1
    #depends_on:
    #  - db
    #links:
    #  - db
    #networks:
    #  - postgresql
    #ports:
    #  - 8000:3000

networks:
  postgresql:
      driver: bridge